naam = ("sheikh abdulla: ")
umar = int(input("Tumhari umar: "))
print(f"Hello {naam}! agle saal tum {umar + 1} saal ke ho jaoge.")
a = int(input("pahla number: "))
b = int(input("doosra number: "))
print(f"Jod = {a + b}")
naam = input( "Tumhara naam kya hai? ")
umar = input("Tumahari age kya hai? ")
saher = input("Tum kaha rahte ho? ")
print("hii", naam, umar, saher)
print( 210 + 105 )
print( 33 * 11 )
print( 41 / 27 )
print( 350 - 35 )
umar = 15 
print(umar + 10 )